name: Publish release AAB artifact

on:
  pull_request:
    branches: [master]

env:
  KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
  RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

jobs:
  publish-release-artifacts:
    name: Publish release

    runs-on: ubuntu-latest

    if: ${{ startsWith(github.head_ref, 'release/') }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Checkout secret repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.KEYSTORE_GIT_REPO }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: ${{ secrets.KEYSTORE_REPO_TARGET }}

      - name: Move google-services to app folder
        run: mv "${{ secrets.KEYSTORE_REPO_TARGET }}/google-services.json" app

      - name: Grant execute permission for sh scripts
        run: |
          chmod +x gradlew
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/tag-release.sh"
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/update-version-code-and-name.sh"
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/push-updated-version.sh"

      - name: Get release name
        run: |
          branch="$GITHUB_HEAD_REF"
          releaseName="${branch#*/}"
          echo "release_name=$releaseName" >> $GITHUB_ENV

      - name: Update release name and version
        run: |
          "${GITHUB_WORKSPACE}"/.github/workflows/update-version-code-and-name.sh ${GITHUB_HEAD_REF} ${GITHUB_REPOSITORY} ${GITHUB_WORKSPACE} "${{ env.release_name }}" ${GITHUB_TOKEN}

      - name: Build release AAB
        run: ./gradlew bundleRelease --stacktrace

      - name: Deploy to beta track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: "${{ secrets.KEYSTORE_REPO_TARGET }}/service_account.json"
          packageName: kozyriatskyi.anton.sked
          releaseFiles: app/build/outputs/bundle/release/*.aab
          track: beta
          userFraction: 0.1
          status: inProgress
          whatsNewDirectory: distribution/changelog
          mappingFile: app/build/outputs/mapping/release/mapping.txt

      - name: Tag release version
        run: |
         "${GITHUB_WORKSPACE}"/.github/workflows/tag-release.sh "${{ env.release_name }}"

      - name: Push updated version
        run: |
          "${GITHUB_WORKSPACE}"/.github/workflows/push-updated-version.sh "${GITHUB_WORKSPACE}" "${{ env.release_name }}" "${GITHUB_TOKEN}"