name: Publish release artifacts

on:
  pull_request:
    branches: [master]

env:
  KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
  RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

jobs:
  build-release-artifacts:
    name: Publish release

    runs-on: ubuntu-latest

    if: ${{ startsWith(github.head_ref, 'release/') || github.head_ref == 'chore/ci-deploy' }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Checkout secret repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.KEYSTORE_GIT_REPO }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: ${{ secrets.KEYSTORE_REPO_TARGET }}

      - name: Move google-services to app folder
        run: mv "${{ secrets.KEYSTORE_REPO_TARGET }}/google-services.json" app

      - name: Grant execute permission for sh  scripts
        run: |
          chmod +x gradlew
          chmod +x "${GITHUB_WORKSPACE}/.github/workflows/"

      - name: Get release name
        run: |
          branch="$GITHUB_HEAD_REF"
          releaseName="${branch#*/}"
          echo "name=release_name::$releaseName" >> $GITHUB_ENV

      - name: Update release name and version
        run: |
          echo "GITHUB_BASE_REF $GITHUB_BASE_REF"
          echo "GITHUB_HEAD_REF $GITHUB_HEAD_REF"
          echo "GITHUB_REF $GITHUB_REF"
          echo "GITHUB_REF_NAME $GITHUB_REF_NAME"

          kotlinc -script "${GITHUB_WORKSPACE}/.github/workflows/update-release-version.kts" -- --name "1.9.0" --workspace "${GITHUB_WORKSPACE}"

          git config --local user.email "GitHub CI"
          git config --local user.name "gh"
          git add "${GITHUB_WORKSPACE}/app/build.gradle"
          git commit -m "Release ${{ env.release_name }} [skip-ci]"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Build release APK
        run: ./gradlew assembleRelease --stacktrace

      - name: Build release AAB
        run: ./gradlew bundleRelease --stacktrace

      - name: Update release name and version
        run: |
          kotlinc -script "${GITHUB_WORKSPACE}/.github/workflows/update-release-version.kts" -- --name "${{ env.release_name }}" --workspace "${GITHUB_WORKSPACE}"

      - name: Deploy to alpha track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: "${{ secrets.KEYSTORE_REPO_TARGET }}/service_account.json"
          packageName: kozyriatskyi.anton.sked
          releaseFiles: app/build/outputs/bundle/release/*.aab,app/build/outputs/apk/release/*.apk,
          track: draft
          userFraction: 0.1
          whatsNewDirectory: distribution/changelog
          mappingFile: app/build/outputs/mapping/release/mapping.txt

      - name: Tag release version
        run: |
         "${GITHUB_WORKSPACE}/.github/workflows/tag-release.sh ${{ env.RELEASE_NAME }}"
