name: Build debug artifacts

on:
  push:
    branches: [dev]

  pull_request:
    branches: [master, dev]

env:
  KEYSTORE_FILE: ${{ secrets.KEYSTORE_FILE }}
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
  RELEASE_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

jobs:
  build-debug-artifacts:
    name: Build debug apk and appbundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Checkout secret repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.KEYSTORE_GIT_REPO }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: ${{ secrets.KEYSTORE_REPO_TARGET }}

      - name: Move google-services to app folder
        run: mv "${{ secrets.KEYSTORE_REPO_TARGET }}/google-services.json" app

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug APK
        run: |
          ./gradlew assembleDebug --stacktrace

      - name: Build debug AAB
        run: |
          ./gradlew bundleDebug --stacktrace


