name: Build debug artifacts

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
  RELEASE_SIGN_KEY_ALIAS: ${{ secrets.RELEASE_KEY_ALIAS }}
  RELEASE_SIGN_KEY_PASSWORD: ${{ secrets.RELEASE_KEY_PASSWORD }}

jobs:
  build_apk_aab:
    name: Build debug artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Checkout keystore repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.KEYSTORE_GIT_REPO }}
          token: ${{ secrets.KEYSTORE_ACCESS_TOKEN }}
          path: ${{ secrets.KEYSTORE_REPO_TARGET }}

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build debug APK
        run: |
          ./gradlew assembleDebug --stacktrace

      - name: Build debug AAB
        run: |
          ./gradlew bundleDebug --stacktrace


